package com.shopkeeper.linh.seeders;

import com.shopkeeper.linh.models.Feedback;
import com.shopkeeper.linh.models.FeedbackType;
import com.shopkeeper.linh.models.SaleBill;
import com.shopkeeper.mediaone.database.DatabaseAdapter;

import java.time.LocalDate;

public class FeedbackSeeder {
    public static void SeedData(){
        var adapter = DatabaseAdapter.getDbAdapter();
        var products = adapter.getAllProducts();
        var musics = adapter.getAllMusicInfos();
        var films = adapter.getAllFilmInfos();
        var books = adapter.getAllBookInfos();
        var staffs = adapter.getAllStaffs();

        Feedback[] list = {
                new Feedback("Nhân viên nói chuyện duyên.", "Tôi thích lắm, nhớ tuyển thêm mấy bạn như thế nhé nhé.",
                        FeedbackType.Satisfied, staffs.get(8), false, LocalDate.of(2020,2,12)),
                new Feedback("Gacha phim hay: Dịch vụ tuyệt quá.", "Tôi thích lắm, nhớ mở thêm những dịch vụ tương tự nhé.",
                        FeedbackType.Satisfied, false, LocalDate.of(2022,3,12)),
                new Feedback("Sản phẩm hơi ít hàng", "Tôi muốn có nhiều hơn",
                        FeedbackType.Unsatisfied, products.get(69), false, LocalDate.of(2021,1,6)),
                new Feedback("Bộ sách ghét ghê.", "Chả đầu tư gì, coi thường người mua.",
                        FeedbackType.Unsatisfied, books.get(11), 2, false, LocalDate.of(2020, 7, 13)),
                new Feedback("Sản phẩm hơi ít hàng", "Tôi muốn có nhiều hơn",
                        FeedbackType.Satisfied, products.get(109), false, LocalDate.of(2021,1,6)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Suggestions, products.get(57), false, LocalDate.of(2019,10,24)),
                new Feedback("Sản phẩm hơi ít hàng", "Tôi muốn có nhiều hơn",
                        FeedbackType.Unsatisfied, products.get(35), false, LocalDate.of(2021,3,22)),
                new Feedback("Nhân viên giọng ngọt.", ":) Nghe tư vấn rất hay, tôi sẽ ủng hộ thêm nhiều nhiều.",
                        FeedbackType.Suggestions, staffs.get(12), false, LocalDate.of(2019,12,7)),
                new Feedback("Gacha đĩa nhạc: Dịch vụ tuyệt quá.", "Tôi nhận được sản phẩm vippro nên rất iu.",
                        FeedbackType.Satisfied, false, LocalDate.of(2019,2,23)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Unsatisfied, products.get(155), false, LocalDate.of(2020,4,18)),
                new Feedback("Sản phẩm hơi ít hàng", "Tôi muốn có nhiều hơn",
                        FeedbackType.Satisfied, products.get(6), false, LocalDate.of(2019,11,8)),
                new Feedback("Sản phẩm xịn", "Cửa hàng uy tín quá",
                        FeedbackType.Suggestions, products.get(163), false, LocalDate.of(2019,5,18)),
                new Feedback("Nhân viên quá tệ.", "Nhân viên cướp bồ của tôi.",
                        FeedbackType.Unsatisfied, staffs.get(20), false, LocalDate.of(2020,10,11)),
                new Feedback("Nhân viên tàm tạm.", "Tư vấn chưa được chi tiết.",
                        FeedbackType.Unsatisfied, staffs.get(21), false, LocalDate.of(2020,4,27)),
                new Feedback("Gacha đĩa nhạc: Dịch vụ cần thay đổi cải thiện.", "Cần xem lại cách triển khai.",
                        FeedbackType.Unsatisfied, false, LocalDate.of(2020,5,30)),
                new Feedback("Nhân viên đẹp trai.", ":) Nghe tư vấn rất hay, tôi sẽ ủng hộ thêm nhiều nhiều.",
                        FeedbackType.Satisfied, staffs.get(4), false, LocalDate.of(2020,9,8)),
                new Feedback("Bộ phim tạm tạm.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Unsatisfied, films.get(18), 2, false, LocalDate.of(2021, 5, 3)),
                new Feedback("Sản phẩm xịn", "Cửa hàng uy tín quá",
                        FeedbackType.Satisfied, products.get(56), false, LocalDate.of(2021,7,19)),
                new Feedback("Mua sách tặng poster wibu: Dịch vụ đáng đồng tiền bát gạo.", "Tôi thích lắm, nhớ mở thêm những dịch vụ tương tự nhé.",
                        FeedbackType.Satisfied, false, LocalDate.of(2022,5,14)),
                new Feedback("Nhân viên quá tệ.", "Tư vấn cục súc, dám nói với tôi \"Mua thì mua không mua thì cút\".",
                        FeedbackType.Satisfied, staffs.get(15), false, LocalDate.of(2020,10,9)),
                new Feedback("Gacha phim hay: Dịch vụ cần bổ sung thêm tiện tích.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Suggestions, false, LocalDate.of(2021,1,14)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Satisfied, products.get(55), false, LocalDate.of(2021,3,25)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Unsatisfied, products.get(7), false, LocalDate.of(2022,2,9)),
                new Feedback("Gacha sách xịn: Dịch vụ cần bổ sung thêm tiện tích.", "Tôi chỉ đóng góp thế thôi.",
                        FeedbackType.Suggestions, false, LocalDate.of(2019,6,5)),
                new Feedback("Nhân viên tệ hại.", "Nhân viên đấm khách.",
                        FeedbackType.Unsatisfied, staffs.get(5), false, LocalDate.of(2019,7,5)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Unsatisfied, products.get(79), false, LocalDate.of(2021,6,4)),
                new Feedback("Bản nhạc tạm tạm.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Suggestions, musics.get(16), 3, false, LocalDate.of(2022, 4, 15)),
                new Feedback("Nhân viên tàm tạm.", "Chỉ cho xem một số món hàng.",
                        FeedbackType.Unsatisfied, staffs.get(18), false, LocalDate.of(2021,4,8)),
                new Feedback("Hộp đẹp đựng đĩa: Dịch vụ rất sáng tạo.", ":) Dịch vụ hay ho lắm.",
                        FeedbackType.Satisfied, false, LocalDate.of(2019,4,6)),
                new Feedback("Bản nhạc tuyệt vời.", "Yeahhhh cuối cùng cũng mua được.",
                        FeedbackType.Unsatisfied, musics.get(14), 2, false, LocalDate.of(2019, 6, 27)),
                new Feedback("Nhân viên cần thay đổi cải thiện.", "Tư vấn cục súc, dám nói với tôi \"Mua thì mua không mua thì cút\".",
                        FeedbackType.Satisfied, staffs.get(11), false, LocalDate.of(2022,5,9)),
                new Feedback("Hộp đẹp đựng đĩa: Dịch vụ tuyệt vời.", "Tôi thích lắm, nhớ mở thêm những dịch vụ tương tự nhé.",
                        FeedbackType.Satisfied, false, LocalDate.of(2020,7,18)),
                new Feedback("Bản nhạc tạm tạm.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Unsatisfied, musics.get(13), 5, false, LocalDate.of(2019, 5, 7)),
                new Feedback("Bọc sách: Dịch vụ rất sáng tạo.", "Tôi thích lắm, nhớ mở thêm những dịch vụ tương tự nhé.",
                        FeedbackType.Satisfied, false, LocalDate.of(2019,4,19)),
                new Feedback("Gacha sách xịn: Dịch vụ cần thêm nhân viên.", "Tôi chỉ đóng góp thế thôi.",
                        FeedbackType.Suggestions, false, LocalDate.of(2020,7,5)),
                new Feedback("Nhân viên nói chuyện duyên.", "Tôi thích lắm, nhớ tuyển thêm mấy bạn như thế nhé nhé.",
                        FeedbackType.Satisfied, staffs.get(22), false, LocalDate.of(2020,3,30)),
                new Feedback("Sản phẩm hơi ít hàng", "Tôi muốn có nhiều hơn",
                        FeedbackType.Satisfied, products.get(49), false, LocalDate.of(2021,6,16)),
                new Feedback("Nhân viên quá tệ.", "Nhân viên đấm khách.",
                        FeedbackType.Satisfied, staffs.get(29), false, LocalDate.of(2021,7,31)),
                new Feedback("Bộ sách tệ hại.", "Haizzz, ước gì nó tốt hơn chứ thế này thì tệ quá.",
                        FeedbackType.Unsatisfied, books.get(19), 4, false, LocalDate.of(2022, 3, 17)),
                new Feedback("Nhân viên xinh.", "Tôi thích lắm, nhớ tuyển thêm mấy bạn như thế nhé nhé.",
                        FeedbackType.Suggestions, staffs.get(19), false, LocalDate.of(2019,6,29)),
                new Feedback("Sản phẩm xịn", "Cửa hàng uy tín quá",
                        FeedbackType.Satisfied, products.get(9), false, LocalDate.of(2020,11,28)),
                new Feedback("Nhân viên tàm tạm.", "Chỉ tư vấn vừa đủ.",
                        FeedbackType.Suggestions, staffs.get(22), false, LocalDate.of(2019,1,12)),
                new Feedback("Bộ phim rất sáng tạo.", "Tôi thích lắm, nhớ nhập thêm những thứ thú vị thế này nhé.",
                        FeedbackType.Suggestions, films.get(10), 2, false, LocalDate.of(2020, 7, 6)),
                new Feedback("Nhân viên tệ hại.", "Nhân viên đấm khách.",
                        FeedbackType.Unsatisfied, staffs.get(5), false, LocalDate.of(2020,3,24)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Unsatisfied, products.get(111), false, LocalDate.of(2022,4,3)),
                new Feedback("Bộ phim tạm tạm.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Suggestions, films.get(16), 2, false, LocalDate.of(2022, 4, 14)),
                new Feedback("Gacha sách xịn: Dịch vụ đáng đồng tiền bát gạo.", "Tôi thích lắm, nhớ mở thêm những dịch vụ tương tự nhé.",
                        FeedbackType.Satisfied, false, LocalDate.of(2022,5,4)),
                new Feedback("Sản phẩm hơi ít hàng", "Tôi muốn có nhiều hơn",
                        FeedbackType.Satisfied, products.get(29), false, LocalDate.of(2019,12,27)),
                new Feedback("Bộ sách tạm tạm.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Unsatisfied, books.get(14), 3, false, LocalDate.of(2022, 2, 17)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Unsatisfied, products.get(158), false, LocalDate.of(2021,6,16)),
                new Feedback("Nhân viên không chấp nhận được.", "Nhân viên cướp bồ của tôi.",
                        FeedbackType.Satisfied, staffs.get(16), false, LocalDate.of(2020,10,21)),
                new Feedback("Nhân viên tàm tạm.", "Chỉ cho xem một số món hàng.",
                        FeedbackType.Unsatisfied, staffs.get(11), false, LocalDate.of(2021,9,6)),
                new Feedback("Nhân viên cần thay đổi cải thiện.", "Nhân viên cướp bồ của tôi.",
                        FeedbackType.Suggestions, staffs.get(22), false, LocalDate.of(2021,6,19)),
                new Feedback("Bộ sách tuyệt vời.", "Quá thú vị, quá hay ho, quá ao chình.",
                        FeedbackType.Unsatisfied, books.get(0), 1, false, LocalDate.of(2019, 1, 26)),
                new Feedback("Mua sách tặng poster wibu: Dịch vụ cần thêm nhân viên.", "Tôi chỉ đóng góp thế thôi.",
                        FeedbackType.Suggestions, false, LocalDate.of(2021,11,20)),
                new Feedback("Nhân viên quá tệ.", "Tư vấn cục súc, dám nói với tôi \"Mua thì mua không mua thì cút\".",
                        FeedbackType.Satisfied, staffs.get(6), false, LocalDate.of(2020,7,20)),
                new Feedback("Nhân viên tàm tạm.", "Tư vấn chưa được chi tiết.",
                        FeedbackType.Satisfied, staffs.get(9), false, LocalDate.of(2021,9,13)),
                new Feedback("Nhân viên giọng ngọt.", "Tôi thích lắm, nhớ tuyển thêm mấy bạn như thế nhé nhé.",
                        FeedbackType.Unsatisfied, staffs.get(5), false, LocalDate.of(2022,2,16)),
                new Feedback("Nhân viên đẹp trai.", ":) Muốn đến của hàng nhìu nhìu để ngắm mấy bạn làm ở đây.",
                        FeedbackType.Satisfied, staffs.get(23), false, LocalDate.of(2020,1,28)),
                new Feedback("Gacha sách xịn: Dịch vụ cần bổ sung thêm tiện tích.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Suggestions, false, LocalDate.of(2021,7,27)),
                new Feedback("Nhân viên tàm tạm.", "Chỉ tư vấn vừa đủ.",
                        FeedbackType.Unsatisfied, staffs.get(12), false, LocalDate.of(2020,9,12)),
                new Feedback("Mua sách tặng poster wibu: Dịch vụ tuyệt vời.", "Tôi thích lắm, nhớ mở thêm những dịch vụ tương tự nhé.",
                        FeedbackType.Satisfied, false, LocalDate.of(2021,12,26)),
                new Feedback("Sản phẩm xịn", "Cửa hàng uy tín quá",
                        FeedbackType.Unsatisfied, products.get(33), false, LocalDate.of(2021,3,29)),
                new Feedback("Sản phẩm hơi ít hàng", "Tôi muốn có nhiều hơn",
                        FeedbackType.Suggestions, products.get(12), false, LocalDate.of(2019,3,14)),
                new Feedback("Nhân viên tàm tạm.", "Tư vấn chưa được chi tiết.",
                        FeedbackType.Satisfied, staffs.get(17), false, LocalDate.of(2021,7,30)),
                new Feedback("Bản nhạc rất sáng tạo.", "Tôi thích lắm, nhớ nhập thêm những thứ thú vị thế này nhé.",
                        FeedbackType.Satisfied, musics.get(1), 4, false, LocalDate.of(2021, 1, 16)),
                new Feedback("Gacha sách xịn: Dịch vụ đáng đồng tiền bát gạo.", "Tôi nhận được sản phẩm vippro nên rất iu.",
                        FeedbackType.Satisfied, false, LocalDate.of(2020,1,11)),
                new Feedback("Nhân viên đẹp trai.", ":) Nghe tư vấn rất hay, tôi sẽ ủng hộ thêm nhiều nhiều.",
                        FeedbackType.Suggestions, staffs.get(16), false, LocalDate.of(2019,3,5)),
                new Feedback("Bộ sách không chấp nhận được.", "Chả hay gì.",
                        FeedbackType.Suggestions, books.get(1), 1, false, LocalDate.of(2019, 7, 1)),
                new Feedback("Sản phẩm xịn", "Cửa hàng uy tín quá",
                        FeedbackType.Satisfied, products.get(14), false, LocalDate.of(2022,6,22)),
                new Feedback("Sản phẩm hơi ít hàng", "Tôi muốn có nhiều hơn",
                        FeedbackType.Satisfied, products.get(111), false, LocalDate.of(2020,12,23)),
                new Feedback("Sản phẩm xịn", "Cửa hàng uy tín quá",
                        FeedbackType.Satisfied, products.get(120), false, LocalDate.of(2021,8,15)),
                new Feedback("Bộ phim tuyệt vời.", "Tôi thích lắm, nhớ nhập thêm những thứ thú vị thế này nhé.",
                        FeedbackType.Unsatisfied, films.get(12), 3, false, LocalDate.of(2020, 4, 24)),
                new Feedback("Gacha sách xịn: Dịch vụ cần bổ sung thêm tiện tích.", "Tôi chỉ đóng góp thế thôi.",
                        FeedbackType.Suggestions, false, LocalDate.of(2020,9,2)),
                new Feedback("Bản nhạc tệ hại.", "Nội dung chán.",
                        FeedbackType.Satisfied, musics.get(15), 3, false, LocalDate.of(2021, 7, 19)),
                new Feedback("Nhân viên tàm tạm.", "Tư vấn chưa được chi tiết.",
                        FeedbackType.Suggestions, staffs.get(23), false, LocalDate.of(2020,11,17)),
                new Feedback("Nhân viên tệ hại.", "Nhân viên cướp bồ của tôi.",
                        FeedbackType.Satisfied, staffs.get(9), false, LocalDate.of(2022,4,10)),
                new Feedback("Nhân viên tàm tạm.", "Chỉ tư vấn vừa đủ.",
                        FeedbackType.Satisfied, staffs.get(18), false, LocalDate.of(2021,1,26)),
                new Feedback("Hộp đẹp đựng đĩa: Dịch vụ rất sáng tạo.", "Tôi thích lắm, nhớ mở thêm những dịch vụ tương tự nhé.",
                        FeedbackType.Satisfied, false, LocalDate.of(2019,4,29)),
                new Feedback("Sản phẩm xịn", "Cửa hàng uy tín quá",
                        FeedbackType.Satisfied, products.get(136), false, LocalDate.of(2020,11,12)),
                new Feedback("Bộ phim tệ hại.", "Chả hay gì.",
                        FeedbackType.Suggestions, films.get(3), 1, false, LocalDate.of(2022, 1, 18)),
                new Feedback("Bộ phim tạm tạm.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Satisfied, films.get(16), 4, false, LocalDate.of(2019, 7, 25)),
                new Feedback("Sản phẩm hơi ít hàng", "Tôi muốn có nhiều hơn",
                        FeedbackType.Satisfied, products.get(74), false, LocalDate.of(2020,1,29)),
                new Feedback("Bọc sách: Dịch vụ đáng đồng tiền bát gạo.", "Tôi thích lắm, nhớ mở thêm những dịch vụ tương tự nhé.",
                        FeedbackType.Satisfied, false, LocalDate.of(2021,6,17)),
                new Feedback("Nhân viên đẹp trai.", "Tôi thích lắm, nhớ tuyển thêm mấy bạn như thế nhé nhé.",
                        FeedbackType.Satisfied, staffs.get(13), false, LocalDate.of(2020,9,10)),
                new Feedback("Nhân viên tàm tạm.", "Chỉ cho xem một số món hàng.",
                        FeedbackType.Satisfied, staffs.get(0), false, LocalDate.of(2019,6,17)),
                new Feedback("Bộ phim tạm tạm.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Satisfied, films.get(1), 4, false, LocalDate.of(2021, 7, 11)),
                new Feedback("Nhân viên tàm tạm.", "Chỉ tư vấn vừa đủ.",
                        FeedbackType.Unsatisfied, staffs.get(12), false, LocalDate.of(2021,8,26)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Satisfied, products.get(76), false, LocalDate.of(2019,12,4)),
                new Feedback("Hộp đẹp đựng đĩa: Dịch vụ cần bổ sung thêm tiện tích.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Suggestions, false, LocalDate.of(2020,6,27)),
                new Feedback("Bộ phim quá tệ.", "Chả đầu tư gì, coi thường người mua.",
                        FeedbackType.Satisfied, films.get(16), 3, false, LocalDate.of(2020, 12, 2)),
                new Feedback("Bộ sách rất sáng tạo.", "Tôi thích lắm, nhớ nhập thêm những thứ thú vị thế này nhé.",
                        FeedbackType.Satisfied, books.get(12), 5, false, LocalDate.of(2020, 11, 30)),
                new Feedback("Bộ phim tệ hại.", "Nội dung chán.",
                        FeedbackType.Unsatisfied, films.get(0), 5, false, LocalDate.of(2020, 12, 12)),
                new Feedback("Hộp đẹp đựng đĩa: Dịch vụ đáng đồng tiền bát gạo.", "Tôi thích lắm, nhớ mở thêm những dịch vụ tương tự nhé.",
                        FeedbackType.Satisfied, false, LocalDate.of(2021,12,31)),
                new Feedback("Gacha sách xịn: Dịch vụ không chấp nhận được.", "Cần xem lại cách triển khai.",
                        FeedbackType.Unsatisfied, false, LocalDate.of(2021,3,10)),
                new Feedback("Gacha sách xịn: Dịch vụ cần thay đổi cải thiện.", "Cửa hàng yêu thích của tôi không ngờ lại thế này.",
                        FeedbackType.Unsatisfied, false, LocalDate.of(2021,6,7)),
                new Feedback("Gacha phim hay: Dịch vụ rất sáng tạo.", "Tôi thích lắm, nhớ mở thêm những dịch vụ tương tự nhé.",
                        FeedbackType.Satisfied, false, LocalDate.of(2020,1,8)),
                new Feedback("Nhân viên giọng ngọt.", ":) Nghe tư vấn rất hay, tôi sẽ ủng hộ thêm nhiều nhiều.",
                        FeedbackType.Unsatisfied, staffs.get(23), false, LocalDate.of(2021,12,3)),
                new Feedback("Sản phẩm xịn", "Cửa hàng uy tín quá",
                        FeedbackType.Unsatisfied, products.get(35), false, LocalDate.of(2020,8,31)),
                new Feedback("Nhân viên tệ hại.", "Chửi tôi do chỉ xem hàng mà ko mua.",
                        FeedbackType.Unsatisfied, staffs.get(16), false, LocalDate.of(2020,10,5)),
                new Feedback("Bản nhạc tạm tạm.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Unsatisfied, musics.get(12), 4, false, LocalDate.of(2020, 1, 21)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Satisfied, products.get(123), false, LocalDate.of(2021,3,10)),
                new Feedback("Gacha đĩa nhạc: Dịch vụ cần thêm nhân viên.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Suggestions, false, LocalDate.of(2021,3,19)),
                new Feedback("Nhân viên không chấp nhận được.", "Nhân viên đấm khách.",
                        FeedbackType.Suggestions, staffs.get(13), false, LocalDate.of(2022,4,10)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Unsatisfied, products.get(48), false, LocalDate.of(2021,10,1)),
                new Feedback("Bản nhạc ghét ghê.", "Haizzz, ước gì nó tốt hơn chứ thế này thì tệ quá.",
                        FeedbackType.Satisfied, musics.get(2), 4, false, LocalDate.of(2020, 11, 17)),
                new Feedback("Sản phẩm hơi ít hàng", "Tôi muốn có nhiều hơn",
                        FeedbackType.Satisfied, products.get(152), false, LocalDate.of(2021,5,2)),
                new Feedback("Bộ phim tuyệt vời.", "Yeahhhh cuối cùng cũng mua được.",
                        FeedbackType.Satisfied, films.get(15), 1, false, LocalDate.of(2021, 2, 25)),
                new Feedback("Nhân viên tệ hại.", "Tư vấn cục súc, dám nói với tôi \"Mua thì mua không mua thì cút\".",
                        FeedbackType.Unsatisfied, staffs.get(7), false, LocalDate.of(2019,6,25)),
                new Feedback("Hộp đẹp đựng đĩa: Dịch vụ không chấp nhận được.", "Chất lượng quá tệ.",
                        FeedbackType.Unsatisfied, false, LocalDate.of(2021,4,26)),
                new Feedback("Gacha sách xịn: Dịch vụ tuyệt vời.", ":) Dịch vụ hay ho lắm.",
                        FeedbackType.Satisfied, false, LocalDate.of(2020,7,23)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Suggestions, products.get(120), false, LocalDate.of(2022,1,27)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Satisfied, products.get(156), false, LocalDate.of(2019,4,2)),
                new Feedback("Sản phẩm xịn", "Cửa hàng uy tín quá",
                        FeedbackType.Unsatisfied, products.get(57), false, LocalDate.of(2019,8,2)),
                new Feedback("Bộ sách đáng đồng tiền bát gạo.", "Tôi thích lắm, nhớ nhập thêm những thứ thú vị thế này nhé.",
                        FeedbackType.Satisfied, books.get(17), 4, false, LocalDate.of(2021, 9, 24)),
                new Feedback("Mua sách tặng poster wibu: Dịch vụ đáng đồng tiền bát gạo.", "Tôi nhận được sản phẩm vippro nên rất iu.",
                        FeedbackType.Satisfied, false, LocalDate.of(2021,12,23)),
                new Feedback("Nhân viên tệ hại.", "Nhân viên đấm khách.",
                        FeedbackType.Unsatisfied, staffs.get(14), false, LocalDate.of(2021,6,14)),
                new Feedback("Sản phẩm hơi ít hàng", "Tôi muốn có nhiều hơn",
                        FeedbackType.Suggestions, products.get(85), false, LocalDate.of(2019,4,3)),
                new Feedback("Sản phẩm xịn", "Cửa hàng uy tín quá",
                        FeedbackType.Unsatisfied, products.get(29), false, LocalDate.of(2021,6,19)),
                new Feedback("Nhân viên tệ hại.", "Nhân viên cướp bồ của tôi.",
                        FeedbackType.Suggestions, staffs.get(4), false, LocalDate.of(2021,9,23)),
                new Feedback("Nhân viên đẹp trai.", ":) Muốn đến của hàng nhìu nhìu để ngắm mấy bạn làm ở đây.",
                        FeedbackType.Satisfied, staffs.get(9), false, LocalDate.of(2021,3,31)),
                new Feedback("Nhân viên nói chuyện duyên.", ":) Muốn đến của hàng nhìu nhìu để ngắm mấy bạn làm ở đây.",
                        FeedbackType.Suggestions, staffs.get(12), false, LocalDate.of(2020,5,6)),
                new Feedback("Nhân viên giọng ngọt.", ":) Nghe tư vấn rất hay, tôi sẽ ủng hộ thêm nhiều nhiều.",
                        FeedbackType.Suggestions, staffs.get(24), false, LocalDate.of(2022,3,28)),
                new Feedback("Quà tặng người thương: Dịch vụ cần bổ sung thêm tiện tích.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Suggestions, false, LocalDate.of(2020,11,9)),
                new Feedback("Nhân viên nói chuyện duyên.", ":) Muốn đến của hàng nhìu nhìu để ngắm mấy bạn làm ở đây.",
                        FeedbackType.Satisfied, staffs.get(17), false, LocalDate.of(2020,4,28)),
                new Feedback("Nhân viên tàm tạm.", "Chỉ cho xem một số món hàng.",
                        FeedbackType.Unsatisfied, staffs.get(5), false, LocalDate.of(2021,10,26)),
                new Feedback("Bộ sách đáng đồng tiền bát gạo.", "Quá thú vị, quá hay ho, quá ao chình.",
                        FeedbackType.Suggestions, books.get(14), 4, false, LocalDate.of(2021, 6, 11)),
                new Feedback("Nhân viên đẹp trai.", ":) Nghe tư vấn rất hay, tôi sẽ ủng hộ thêm nhiều nhiều.",
                        FeedbackType.Suggestions, staffs.get(0), false, LocalDate.of(2021,1,4)),
                new Feedback("Quà tặng người thương: Dịch vụ cần thay đổi cải thiện.", "Cần xem lại cách triển khai.",
                        FeedbackType.Unsatisfied, false, LocalDate.of(2021,4,1)),
                new Feedback("Nhân viên giọng ngọt.", ":) Nghe tư vấn rất hay, tôi sẽ ủng hộ thêm nhiều nhiều.",
                        FeedbackType.Unsatisfied, staffs.get(19), false, LocalDate.of(2019,12,29)),
                new Feedback("Hộp đẹp đựng đĩa: Dịch vụ cần thay đổi cải thiện.", "Cửa hàng yêu thích của tôi không ngờ lại thế này.",
                        FeedbackType.Unsatisfied, false, LocalDate.of(2021,2,22)),
                new Feedback("Gacha đĩa nhạc: Dịch vụ cần thay đổi cải thiện.", "Cần xem lại cách triển khai.",
                        FeedbackType.Unsatisfied, false, LocalDate.of(2021,10,15)),
                new Feedback("Bản nhạc tuyệt vời.", "Yeahhhh cuối cùng cũng mua được.",
                        FeedbackType.Unsatisfied, musics.get(3), 4, false, LocalDate.of(2020, 7, 3)),
                new Feedback("Bản nhạc tuyệt vời.", "Yeahhhh cuối cùng cũng mua được.",
                        FeedbackType.Suggestions, musics.get(10), 3, false, LocalDate.of(2022, 3, 10)),
                new Feedback("Bản nhạc tạm tạm.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Suggestions, musics.get(15), 2, false, LocalDate.of(2021, 10, 26)),
                new Feedback("Bọc sách: Dịch vụ đáng đồng tiền bát gạo.", "Tôi thích lắm, nhớ mở thêm những dịch vụ tương tự nhé.",
                        FeedbackType.Satisfied, false, LocalDate.of(2019,4,19)),
                new Feedback("Hộp đẹp đựng đĩa: Dịch vụ cần thêm nhân viên.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Suggestions, false, LocalDate.of(2021,12,31)),
                new Feedback("Sản phẩm hơi ít hàng", "Tôi muốn có nhiều hơn",
                        FeedbackType.Satisfied, products.get(16), false, LocalDate.of(2019,6,1)),
                new Feedback("Sản phẩm xịn", "Cửa hàng uy tín quá",
                        FeedbackType.Satisfied, products.get(28), false, LocalDate.of(2020,7,26)),
                new Feedback("Nhân viên quá tệ.", "Nhân viên cướp bồ của tôi.",
                        FeedbackType.Satisfied, staffs.get(8), false, LocalDate.of(2022,4,9)),
                new Feedback("Nhân viên quá tệ.", "Nhân viên đấm khách.",
                        FeedbackType.Satisfied, staffs.get(19), false, LocalDate.of(2019,11,20)),
                new Feedback("Nhân viên xinh.", "Tôi thích lắm, nhớ tuyển thêm mấy bạn như thế nhé nhé.",
                        FeedbackType.Unsatisfied, staffs.get(8), false, LocalDate.of(2019,8,20)),
                new Feedback("Bản nhạc tạm tạm.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Suggestions, musics.get(5), 1, false, LocalDate.of(2021, 3, 19)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Satisfied, products.get(116), false, LocalDate.of(2021,5,28)),
                new Feedback("Bộ phim không chấp nhận được.", "Haizzz, ước gì nó tốt hơn chứ thế này thì tệ quá.",
                        FeedbackType.Satisfied, films.get(15), 4, false, LocalDate.of(2020, 5, 18)),
                new Feedback("Bộ sách đáng đồng tiền bát gạo.", "Quá thú vị, quá hay ho, quá ao chình.",
                        FeedbackType.Satisfied, books.get(2), 4, false, LocalDate.of(2021, 7, 23)),
                new Feedback("Gacha sách xịn: Dịch vụ tuyệt vời.", "Tôi thích lắm, nhớ mở thêm những dịch vụ tương tự nhé.",
                        FeedbackType.Satisfied, false, LocalDate.of(2019,10,23)),
                new Feedback("Bản nhạc tệ hại.", "Chả hay gì.",
                        FeedbackType.Suggestions, musics.get(1), 3, false, LocalDate.of(2019, 10, 10)),
                new Feedback("Nhân viên không chấp nhận được.", "Tư vấn cục súc, dám nói với tôi \"Mua thì mua không mua thì cút\".",
                        FeedbackType.Suggestions, staffs.get(24), false, LocalDate.of(2019,8,18)),
                new Feedback("Nhân viên tàm tạm.", "Chỉ cho xem một số món hàng.",
                        FeedbackType.Unsatisfied, staffs.get(14), false, LocalDate.of(2022,3,22)),
                new Feedback("Nhân viên tàm tạm.", "Chỉ tư vấn vừa đủ.",
                        FeedbackType.Satisfied, staffs.get(18), false, LocalDate.of(2019,1,9)),
                new Feedback("Nhân viên không chấp nhận được.", "Chửi tôi do chỉ xem hàng mà ko mua.",
                        FeedbackType.Suggestions, staffs.get(15), false, LocalDate.of(2019,8,27)),
                new Feedback("Nhân viên giọng ngọt.", "Tôi thích lắm, nhớ tuyển thêm mấy bạn như thế nhé nhé.",
                        FeedbackType.Suggestions, staffs.get(14), false, LocalDate.of(2020,3,4)),
                new Feedback("Nhân viên tàm tạm.", "Tư vấn chưa được chi tiết.",
                        FeedbackType.Suggestions, staffs.get(8), false, LocalDate.of(2020,12,29)),
                new Feedback("Bộ phim quá tệ.", "Chả hay gì.",
                        FeedbackType.Satisfied, films.get(6), 5, false, LocalDate.of(2019, 3, 3)),
                new Feedback("Sản phẩm hơi ít hàng", "Tôi muốn có nhiều hơn",
                        FeedbackType.Unsatisfied, products.get(99), false, LocalDate.of(2022,6,15)),
                new Feedback("Bộ sách đáng đồng tiền bát gạo.", "Yeahhhh cuối cùng cũng mua được.",
                        FeedbackType.Satisfied, books.get(2), 5, false, LocalDate.of(2020, 11, 30)),
                new Feedback("Nhân viên không chấp nhận được.", "Nhân viên cướp bồ của tôi.",
                        FeedbackType.Unsatisfied, staffs.get(13), false, LocalDate.of(2019,12,22)),
                new Feedback("Bộ phim không chấp nhận được.", "Nội dung chán.",
                        FeedbackType.Satisfied, films.get(1), 1, false, LocalDate.of(2021, 3, 10)),
                new Feedback("Bọc sách: Dịch vụ tuyệt vời.", "Tôi thích lắm, nhớ mở thêm những dịch vụ tương tự nhé.",
                        FeedbackType.Satisfied, false, LocalDate.of(2020,5,16)),
                new Feedback("Bản nhạc tạm tạm.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Satisfied, musics.get(18), 2, false, LocalDate.of(2022, 5, 31)),
                new Feedback("Bộ sách tạm tạm.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Suggestions, books.get(1), 5, false, LocalDate.of(2019, 5, 15)),
                new Feedback("Bộ phim quá tệ.", "Haizzz, ước gì nó tốt hơn chứ thế này thì tệ quá.",
                        FeedbackType.Satisfied, films.get(9), 2, false, LocalDate.of(2021, 6, 22)),
                new Feedback("Bản nhạc tuyệt vời.", "Yeahhhh cuối cùng cũng mua được.",
                        FeedbackType.Satisfied, musics.get(17), 5, false, LocalDate.of(2021, 9, 2)),
                new Feedback("Bộ phim tuyệt vời.", "Yeahhhh cuối cùng cũng mua được.",
                        FeedbackType.Satisfied, films.get(7), 2, false, LocalDate.of(2019, 2, 24)),
                new Feedback("Bộ sách tệ hại.", "Nội dung chán.",
                        FeedbackType.Satisfied, books.get(19), 5, false, LocalDate.of(2019, 1, 2)),
                new Feedback("Gacha đĩa nhạc: Dịch vụ tệ hại.", "Chất lượng quá tệ.",
                        FeedbackType.Unsatisfied, false, LocalDate.of(2020,8,13)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Unsatisfied, products.get(83), false, LocalDate.of(2021,6,20)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Satisfied, products.get(173), false, LocalDate.of(2021,10,27)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Suggestions, products.get(159), false, LocalDate.of(2022,3,7)),
                new Feedback("Bộ phim ghét ghê.", "Chả hay gì.",
                        FeedbackType.Satisfied, films.get(13), 1, false, LocalDate.of(2020, 11, 11)),
                new Feedback("Nhân viên giọng ngọt.", ":) Muốn đến của hàng nhìu nhìu để ngắm mấy bạn làm ở đây.",
                        FeedbackType.Satisfied, staffs.get(17), false, LocalDate.of(2022,3,18)),
                new Feedback("Bộ phim tạm tạm.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Satisfied, films.get(14), 4, false, LocalDate.of(2019, 7, 14)),
                new Feedback("Sản phẩm hơi ít hàng", "Tôi muốn có nhiều hơn",
                        FeedbackType.Suggestions, products.get(96), false, LocalDate.of(2021,3,14)),
                new Feedback("Bản nhạc rất sáng tạo.", "Tôi thích lắm, nhớ nhập thêm những thứ thú vị thế này nhé.",
                        FeedbackType.Satisfied, musics.get(3), 5, false, LocalDate.of(2020, 3, 12)),
                new Feedback("Nhân viên giọng ngọt.", ":) Nghe tư vấn rất hay, tôi sẽ ủng hộ thêm nhiều nhiều.",
                        FeedbackType.Unsatisfied, staffs.get(10), false, LocalDate.of(2020,12,10)),
                new Feedback("Hộp đẹp đựng đĩa: Dịch vụ cần bổ sung thêm tiện tích.", "Tôi chỉ đóng góp thế thôi.",
                        FeedbackType.Suggestions, false, LocalDate.of(2021,7,18)),
                new Feedback("Sản phẩm bị lỗi", "Cần được sửa/đổi",
                        FeedbackType.Satisfied, products.get(18), false, LocalDate.of(2020,11,15)),
                new Feedback("Nhân viên tàm tạm.", "Chỉ cho xem một số món hàng.",
                        FeedbackType.Unsatisfied, staffs.get(26), false, LocalDate.of(2019,1,6)),
                new Feedback("Bản nhạc tuyệt quá.", "Tôi thích lắm, nhớ nhập thêm những thứ thú vị thế này nhé.",
                        FeedbackType.Unsatisfied, musics.get(4), 4, false, LocalDate.of(2021, 6, 5)),
                new Feedback("Bộ sách tuyệt vời.", "Yeahhhh cuối cùng cũng mua được.",
                        FeedbackType.Unsatisfied, books.get(3), 4, false, LocalDate.of(2021, 4, 23)),
                new Feedback("Bộ sách tạm tạm.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Suggestions, books.get(6), 4, false, LocalDate.of(2020, 5, 9)),
                new Feedback("Nhân viên nói chuyện duyên.", ":) Muốn đến của hàng nhìu nhìu để ngắm mấy bạn làm ở đây.",
                        FeedbackType.Satisfied, staffs.get(20), false, LocalDate.of(2021,3,15)),
                new Feedback("Gacha phim hay: Dịch vụ cần bổ sung thêm tiện tích.", "Tôi chỉ đóng góp thế thôi.",
                        FeedbackType.Suggestions, false, LocalDate.of(2020,3,6)),
                new Feedback("Bản nhạc tuyệt quá.", "Yeahhhh cuối cùng cũng mua được.",
                        FeedbackType.Satisfied, musics.get(16), 5, false, LocalDate.of(2019, 1, 31)),
                new Feedback("Sản phẩm xịn", "Cửa hàng uy tín quá",
                        FeedbackType.Suggestions, products.get(159), false, LocalDate.of(2020,4,9)),
                new Feedback("Bản nhạc tạm tạm.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Suggestions, musics.get(17), 1, false, LocalDate.of(2020, 9, 4)),
                new Feedback("Bọc sách: Dịch vụ tuyệt quá.", ":) Dịch vụ hay ho lắm.",
                        FeedbackType.Satisfied, false, LocalDate.of(2021,8,22)),
                new Feedback("Nhân viên quá tệ.", "Nhân viên đấm khách.",
                        FeedbackType.Satisfied, staffs.get(6), false, LocalDate.of(2020,1,25)),
                new Feedback("Nhân viên xinh.", ":) Nghe tư vấn rất hay, tôi sẽ ủng hộ thêm nhiều nhiều.",
                        FeedbackType.Unsatisfied, staffs.get(7), false, LocalDate.of(2021,4,7)),
                new Feedback("Nhân viên quá tệ.", "Nhân viên đấm khách.",
                        FeedbackType.Unsatisfied, staffs.get(8), false, LocalDate.of(2022,6,12)),
                new Feedback("Bản nhạc tạm tạm.", "Tôi chỉ góp ý nhẹ nhàng thế thôi.",
                        FeedbackType.Suggestions, musics.get(5), 1, false, LocalDate.of(2021, 8, 12)),
                new Feedback("Nhân viên tàm tạm.", "Tư vấn chưa được chi tiết.",
                        FeedbackType.Satisfied, staffs.get(23), false, LocalDate.of(2021,8,4)),
                new Feedback("Sản phẩm xịn", "Cửa hàng uy tín quá",
                        FeedbackType.Suggestions, products.get(59), false, LocalDate.of(2022,1,12)),
                new Feedback("Nhân viên tệ hại.", "Nhân viên đấm khách.",
                        FeedbackType.Unsatisfied, staffs.get(25), false, LocalDate.of(2021,7,5)),
                new Feedback("Hộp đẹp đựng đĩa: Dịch vụ rất sáng tạo.", "Tôi thích lắm, nhớ mở thêm những dịch vụ tương tự nhé.",
                        FeedbackType.Satisfied, false, LocalDate.of(2021,2,25)),
                new Feedback("Bộ sách đáng đồng tiền bát gạo.", "Tôi thích lắm, nhớ nhập thêm những thứ thú vị thế này nhé.",
                        FeedbackType.Suggestions, books.get(18), 5, false, LocalDate.of(2019, 2, 9)),
                new Feedback("Nhân viên đẹp trai.", "Tôi thích lắm, nhớ tuyển thêm mấy bạn như thế nhé nhé.",
                        FeedbackType.Satisfied, staffs.get(22), false, LocalDate.of(2019,1,1)),
                new Feedback("Nhân viên tệ hại.", "Chửi tôi do chỉ xem hàng mà ko mua.",
                        FeedbackType.Unsatisfied, staffs.get(16), false, LocalDate.of(2019,10,14)),
                new Feedback("Bọc sách: Dịch vụ quá tệ.", "Cần xem lại cách triển khai.",
                        FeedbackType.Unsatisfied, false, LocalDate.of(2021,2,10)),
        };
        for(var x : list){
            adapter.insertFeedback(x);
        }
    }
}
