package com.shopkeeper.linh.seeders;

import com.shopkeeper.linh.models.Customer;
import com.shopkeeper.linh.models.SaleBill;
import com.shopkeeper.mediaone.database.DatabaseAdapter;

import java.time.LocalDate;

public class SaleBillSeeder {
    public static void SeedData(){
        var adapter = DatabaseAdapter.getDbAdapter();
        var customers = adapter.getAllCustomers();
        SaleBill[] list = {
                new SaleBill("Hoá đơn ngày 6/1/2021", customers.get(0), "Ngõ 97 Đ. Nguyễn Chí Thanh, Láng Hạ, Đống Đa, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2021,1,6), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 5/9/2019", customers.get(1), "113A2 P. Thành Công, Thành Công, Ba Đình, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2019,9,5), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 30/3/2021", customers.get(2), "102 E2 P. Thành Công, Thành Công, Ba Đình, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2021,3,30), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 8/9/2021", customers.get(3), "25/612/50, Đường La Thành, Phường Giảng Võ, Quận Ba Đình, Giảng Võ, Ba Đình, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2021,9,8), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 22/10/2021", customers.get(4), "599 Đ. La Thành, Thành Công, Ba Đình, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2021,10,22), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 9/4/2020", customers.get(5), "5 P. Láng Hạ, Thành Công, Ba Đình, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2020,4,9), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 7/2/2021", customers.get(6), "187 P. Giảng Võ, Chợ Dừa, Đống Đa, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2021,2,7), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 16/7/2019", customers.get(7), "135 P. An Trạch, Chợ Dừa, Đống Đa, Hà Nội 100000, Vietnam",
                        true, 0, LocalDate.of(2019,7,16), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 1/1/2020", customers.get(8), "84 P. Trần Hữu Tước, Nam Đồng, Đống Đa, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2020,1,1), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 11/1/2019", customers.get(9), "338 P. Xã Đàn, Phương Liên, Đống Đa, Hà Nội 100000, Vietnam",
                        true, 0, LocalDate.of(2019,1,11), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 11/2/2020", customers.get(10), "97C Đại Cồ Việt, Bách Khoa, Hai Bà Trưng, Hà Nội 10000, Vietnam",
                        true, 0, LocalDate.of(2020,2,11), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 3/6/2022", customers.get(11), "29 P. Trần Đại Nghĩa, Bách Khoa, Hai Bà Trưng, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2022,6,3), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 11/12/2020", customers.get(12), "10 P. Tạ Quang Bửu, Bách Khoa, Hai Bà Trưng, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2020,12,11), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 28/2/2022", customers.get(13), "91 P. Trần Đại Nghĩa, Bách Khoa, Hai Bà Trưng, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2022,2,28), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 10/8/2019", customers.get(14), "92 A P. Lê Thanh Nghị, Bách Khoa, Hai Bà Trưng, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2019,8,10), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 8/6/2020", customers.get(15), "373 Bạch Mai, Hai Bà Trưng, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2020,6,8), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 6/4/2021", customers.get(16), "1 P. Bùi Ngọc Dương, Bạch Mai, Hai Bà Trưng, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2021,4,6), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 13/2/2019", customers.get(17), "189 P. Chùa Quỳnh, P, Hai Bà Trưng, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2019,2,13), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 30/9/2020", customers.get(18), "288 Ng. Quỳnh, Thanh Nhàn, Hai Bà Trưng, Hà Nội 100000, Vietnam",
                        true, 0, LocalDate.of(2020,9,30), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 13/5/2019", customers.get(19), "238 P. Minh Khai, Minh Khai, Hai Bà Trưng, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2019,5,13), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 9/10/2021", customers.get(20), "25 Trương Định, Hai Bà Trưng, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2021,10,9), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 19/6/2019", customers.get(21), "164 Trương Định, Hoàng Mai, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2019,6,19), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 1/9/2019", customers.get(22), "4 P. Vọng, Đồng Tâm, Đống Đa, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2019,9,1), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 4/2/2022", customers.get(23), "36 Ng. 259 P. Vọng, Đồng Tâm, Hai Bà Trưng, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2022,2,4), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 10/11/2021", customers.get(24), "147 Ng. Trại Cá, Trương Định, Hai Bà Trưng, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2021,11,10), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 3/6/2021", customers.get(25), "10 Ng. Trại Cá, Trương Định, Hai Bà Trưng, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2021,6,3), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 21/1/2022", customers.get(26), "Ngõ 104 Nguyễn An Ninh, Trương Định, Hoàng Mai, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2022,1,21), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 16/3/2022", customers.get(27), "437 Bạch Mai, Trương Định, Hai Bà Trưng, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2022,3,16), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 21/3/2019", customers.get(28), "Ngõ 92 P. Bùi Ngọc Dương, Bạch Mai, Hai Bà Trưng, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2019,3,21), true,
                        "Đã trả tiền."),
                new SaleBill("Hoá đơn ngày 17/11/2020", customers.get(29), "191 Bà Triệu, Lê Đại Hành, Hai Bà Trưng, Hà Nội, Vietnam",
                        true, 0, LocalDate.of(2020,11,17), true,
                        "Đã trả tiền."),
        };
        for(var x : list){
            adapter.insertSaleBill(x);
        }
    }
}
